name: daily-report

on:
  schedule:
    - cron: '0 0 * * *'  # Sends email once a day
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      
      # Step to install dependencies
      - name: Install dependencies
        run: pip install requests
      
      # Step to run the email sending Python code
      - name: Run email code
        env:
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
        run: python send_email.py
